In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('play_tennis.csv')
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [3]:
data.drop(columns=['day'], inplace=True)

In [6]:
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [7]:
data.shape

(14, 5)

In [8]:
# Problem 1

# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# Play or Not Play?

In [9]:
# Solution

# P(Yes | Sunny, Hot, High, Weak) = P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes) * P(Yes)

# P(No | Sunny, Hot, High, Weak) = P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No) * P(No)

# Compare and decide using the Maximum a posteriori rule

In [10]:
# Problem 2

# Outlook=Overcast, Temp=Cold, Humidity=Low, Wind=Weak
# Play or Not Play?

In [ ]:
# Solution

# P(Yes | Overcast, Cold, Low, Weak) = P(Overcast | Yes) * P(Cold | Yes) * P(Low | Yes) * P(Weak | Yes) * P(Yes)

# P(No | Overcast, Cold, Low, Weak) = P(Overcast | No) * P(Cold | No) * P(Low | No) * P(Weak | No) * P(No)

# Compare and decide using the Maximum a posteriori rule

In [ ]:
# There are 2 stages in ML models

# 1. Training 
# 2. Testing

# Naive bayes have Lookup Table that store values in dictionary

In [11]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [13]:
py = 9/14
pn = 5/14

print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [14]:
# Outlook

pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [15]:
# Pon -> probability of overcast for n

Pon = 0
Prn = 2/5
Psn = 3/5

Poy = 4/9
Pry = 3/9
Psy = 2/9

In [16]:
# Temperature

pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [17]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [18]:
# Hokumidity

pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [19]:
PHighNo = 4/5
PNormalNo = 1/5

PHighYes = 3/9
PNormalYes = 6/9

In [20]:
# Wind

pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [21]:
PStrongNo = 3/5
PWeakNo = 2/5

PStrongYes = 3/9
PWeakYes = 6/9

In [22]:
# Now Our Lookup table is Ready!

In [23]:
# Problem 1

# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak

Pyes = py * Psy * PHotYes * PHighYes * PWeakYes

print(Pyes)

0.007054673721340388

In [24]:
Pno = pn * Psn * PHotNo * PHighNo * PWeakNo

print(Pno)

0.02742857142857143

## Conclusion

### Pno > Pyes 
### Answer -> No play